apiVersion: v1
kind: Pod
metadata:
  name: startrek
  namespace: new-name-space
  labels:
    app: myap
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers: 
     - name: nginx-image-container
       image: nginx