apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myap
spec:
  containers: 
     - name: nginx-image-container
       image: nginx
       env:
         - name: app-environment
           value: dev