apiVersion: v1
kind: Pod 
metadata:
  name: manual-env-variable-pod
spec:
  containers:
  - name: manual-env-variable-pod
    image: ubuntu
    ports:
      - containerPort: 8080
    env:
      - name: app_color
        value: pink
    # command: ["sleep 5000"] or
    # command: ["sleep", "5000"] or
    # command:
    # - "sleep"
    # - "5000"
    command: [ "sleep" ]
    args: [ "5000" ]