apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redixpod
  name: redixpod
spec:
  containers:
  - image: redis
    name: redixpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
