apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: webapp
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 31656
  type: NodePort