apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: webapp
  ports:
  - name: nginx
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31704
  - name: http
    # protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31705
  type: NodePort