apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "APLACE app"
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  ports:
  - name: httpd-service
    port: 80
  selector:
    app: httpd
  type: ClusterIP
