apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod-name
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
  nodeSelector:
    size: Large
