apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: redixpod
  name: redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redixpod
status:
  loadBalancer: {}
