apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  # securityContext: # pod-level security
  #     runAsUser: 1000
  containers: # container level security.
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "100"]
        securityContext: # pod-level security
            runAsUser: 1000
            capabilities:
              add: ["MAC_ADMIN"]
