apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-service
  name: myapp-service
spec:
  ports:
  - targetPort: 80
    port: 80
    nodePort: 31235
  selector:
    app: webapp
  type: NodePort
status:
  loadBalancer: {}