apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    version: v2
  ports:
  - name: nginx
    # protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31707
  type: NodePort

  #test
