apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  containers:
  - name: web-app
    image: nginx
    ports:
      - containerPort: 8080
  - name: log-agent
    image: busybox
    ports: 
      - containerPort: 443