apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: readiness-probe
  name: readiness-probe
spec:
  containers:
  - image: nginx
    name: readiness-probe
    resources: {}
    liveinessProbe: # check the application is running or not, even though container is up.
    # livenessProbe periodically checks the application in the container is healthy.
    # if the app is not-healthy, then the container is destroyed and recreated.
      httpGet: # k8s takes the request and response api test. 
        path: /api/ready
        port: 8080
    initalDelaySeconds: 10 #it helps the pod to warm-up.
    periodSeconds: 5 #helps, how often to probe
    failureThresold: 8 # To avoid the default failure attemts 3.
