apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: readiness-probe
  name: readiness-probe
spec:
  containers:
  - image: nginx
    name: readiness-probe
    resources: {}
    readinessProbe:
      httpGet: # k8s takes the request and response api test. 
        path: /api/ready
        port: 8080
    initalDelaySeconds: 10 #it helps the pod to warm-up.
    periodSeconds: 5 #helps, how often to probe
    failureThresold: 8 # To avoid the default failure attemts 3.

    # readinessProbe:
    #   tcpSocket: # k8s takes the request and response api test. 
    #     port: 8080

    # readinessProbe:
    #   exec: # executing a command
    #     command:
    #         - cat
    #         - /app/is_ready