apiVersion: flights.com/v1
kind: FlightTicket #this is from CustomResourceDefinition spec.names.kind field, kind
metadata:
  name: my-flight-ticket
  namespace: default
spec:
  from: Mumbai
  to: London
  number: 2