apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: math-add-job
  name: math-add-job
spec:
  completions: 3 # 3 desired and successful pods, pods are created when the previous pod is created or failure. It will make sure to compelete three pods.
  parallelism: 3 # creates 3 pods parallel
  template:
    spec:
      containers:
      - image: ubuntu
        name: math-add-job
        command: ['expr', '3', '+', '2']
      restartPolicy: Never
