apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: event-simulator
    volumeMounts:
    - mountPath: /log
      name: log-volume #This is volume name
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log/webapp
      type: Directory