apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["/bin/sh","-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.txt;"]
    volumeMounts:
    - mountPath: "/opt"
      name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
    # command: ["shuf -i 0-100 -n 1 >> /tmp/data/number.out;"]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/test"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
      - ReadWriteMany
  resources:
      requests:
        storage: 500Mi