apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
      storage: 500Mi
  awsElasticBlockStore:
    volumeID: "32343"
    fsType: ext4
  # hostPath:
  #     path: /tmp/data
