apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-administrator
  # namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - list
  - get
  - delete