apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
  resourceNames: ["blue", "orange"] ## restrict access to blue, orange pods.
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
