apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-binding ## role binidng name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer ## role name
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user # username