apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
    size: Large
  name: pod-nodeaffinity
spec:
  containers:
  - image: nginx
    name: pod
  affinity:
   nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large
            - Small
